name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: Windows,
            artifact: windows-x64-msdfgen.dll,
            artifact-path: Release/msdfgen.dll,
            os: windows-latest,
          }
        - {
            name: Linux,
            artifact: linux-x64-libmsdfgen.so,
            artifact-path: libmsdfgen.so,
            os: ubuntu-latest,
          }
        - {
            name: Android,
            artifact: android-armeabi-v7a-libmsdfgen.so,
            artifact-path: libmsdfgen.so,
            cmakeArgs: -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a,
            os: windows-latest,
          }

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMSDFGEN_BUILD_SHARED_LIBRARY=ON -DMSDFGEN_BUILD_STANDALONE=OFF -DMSDFGEN_USE_FREETYPE=OFF -DMSDFGEN_INSTALL=OFF ${{matrix.config.cmakeArgs}} -S .

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.config.artifact}}
        path: build/out/${{matrix.config.artifact-path}}
      
